// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;
import "forge-std/Test.sol";
import "../src/UdayGift.sol";

contract MockUSDG is IERC20 {
    mapping(address => uint256) public balanceOf;
    function mint(address to, uint256 a) external { balanceOf[to] += a; }
    function transfer(address to, uint256 a) external returns (bool) {
        balanceOf[msg.sender] -= a; balanceOf[to] += a; return true;
    }
}

contract UdayGiftTest is Test {
    UdayGift g; MockUSDG usdg;
    // values generated by tools/build_gift_root.py for 2026-08-24
    uint32 constant DAY = 20260824;
    bytes32 constant ROOT = 0x332274950abe9b5edefabcecf9ddf76008cf913d90e8b7b5ec5f1cbfd988cce8;
    address constant A1 = 0x02E797524881ed9e188E163914f4ffaeea93eB2F;
    address constant A2 = 0x8b20c990C95d0c97aF12DfAce0D2f0399a3cB870;

    function setUp() public {
        usdg = new MockUSDG();
        g = new UdayGift(address(usdg), address(this));
        usdg.mint(address(g), 10_000_000);
        g.setRoot(DAY, ROOT);
    }
    function proof1() internal pure returns (bytes32[] memory p) {
        p = new bytes32[](1);
        p[0] = 0x792236a7a97a50e123e4e65d55c8c72369e6d53906a1e6f2eac7a88cb7d8be0d;
    }
    function proof2() internal pure returns (bytes32[] memory p) {
        p = new bytes32[](1);
        p[0] = 0x9010cba27c26358bbf74ecb67a1e7ddccf778049cf87acf6d24fd73d8b77ddc1;
    }
    function testClaimBoth() public {
        g.claim(DAY, A1, 1_000_000, proof1());
        g.claim(DAY, A2, 1_000_000, proof2());
        assertEq(usdg.balanceOf(A1), 1_000_000);
        assertEq(usdg.balanceOf(A2), 1_000_000);
    }
    function testDoubleClaimReverts() public {
        g.claim(DAY, A1, 1_000_000, proof1());
        vm.expectRevert(UdayGift.AlreadyClaimed.selector);
        g.claim(DAY, A1, 1_000_000, proof1());
    }
    function testWrongAmountReverts() public {
        vm.expectRevert(UdayGift.BadProof.selector);
        g.claim(DAY, A1, 2_000_000, proof1());
    }
    function testWindowCloses() public {
        vm.warp(block.timestamp + 49 hours);
        vm.expectRevert(UdayGift.WindowClosed.selector);
        g.claim(DAY, A1, 1_000_000, proof1());
    }
    function testRootImmutable() public {
        vm.expectRevert(UdayGift.AlreadyPosted.selector);
        g.setRoot(DAY, bytes32(uint256(1)));
    }
}
